### ISSUE TITLE
General AI Development Tracker

### ISSUE THREAD

**Issue by lovalmidas** [nguoiyoujie/SWEndor#4]
Divided into two main categories

**ActionInfo**
- [X]  [Evade] To honor AI Bounds, preventing evasion into forbidden zones.
- [x]  [AvoidCollisionRotate] Smarter collision avoidance
- [x]  [Hunt] Devise a way to improve Actor scan to pick targets with less resources.
- [x]  [SmartHunt] Improved version of Hunt to pick targets based on effectiveness (Y-Wings against cruisers, X-Wings against TIEs) _Integrated as part of Hunt_

**ActorInfo (overriding controls over ActionInfo settings)**
- [ ]  Blocking controls to override automatic AI actions
 - [X]  NoAI (Disables AI processing, but does not clear the list - clearing the Action list to be performed separately)
 - [X]  CanEvade (switches AI to Evade if under attack)
 - [X]  CanRetaliate (switches AI to AttackActor if under attack)
 - [X]  HuntWeight (influences the probability of picking targets)
 - [ ]  NoIdleHunt (Disables AI turning into Hunt mode when idle)

**Parser Development**
 - [ ] Create an ActionFactory and ActionParser class to process strings into ActionInfo.
